<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Web App Pokemons - <?=$title?></title>
    <link rel="stylesheet" href="<?=$css?>/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="<?=$css?>/bootstrap.min.css">
    <link rel="stylesheet" href="<?=$css?>/fontawesome.min.css">
    <link rel="stylesheet" href="<?=$css?>/fonts.css">
</head>
<body>